### ISSUE TITLE
Bad checksum remains

### ISSUE THREAD

**Issue by AlainCas** [YunoHost-Apps/pmwiki_ynh#18]
I'm sorry, but the problem ( https://github.com/YunoHost-Apps/pmwiki_ynh/issues/16 ) remains even when trying the testing branch :
69273 DEBUG Prefetching asset main: https://www.pmwiki.org/pub/pmwiki/pmwiki-2.3.32.zip ...
70579 DEBUG Prefetching asset fr: http://www.pmwiki.org/pub/pmwiki/i18n/i18n-fr.zip ...
72084 WARNING Failed to provision sources : YunoHost a pu télécharger la ressource 'fr' (http://www.pmwiki.org/pub/pmwiki/i18n/i18n-fr.zip) pour pmwiki, malheureusement celle-ci ne correspond pas à la somme des contrôles attendue. Cela peut signifier qu'une défaillance temporaire du réseau s'est produite sur votre serveur, OU que la ressource a été modifiée par le mainteneur de l'application en amont (ou un acteur malveillant ?) et que les responsables du paquet de cette application pour YunoHost doivent investiguer et mettre à jour le manifeste de l'application pour indiquer ce changement.
    Somme de contrôle sha256 attendue : edc1e591f0d901cda90d4ab3a4e6b4d0f6a910454a35837a15a361dc6520354d
    Somme de contrôle sha256 téléchargée : 0bedd50a56777b8568f2e7a8e291aa5c38c62a9a5c62c9d30d53a7c9eef5c004
    Taille du fichier téléchargé : 684K
72085 INFO Deprovisioning sources...
72085 ERROR L'allocation automatique des ressources (provisioning), la suppression d'accès à ces ressources (déprovisioning) ou la mise à jour des ressources pour pmwiki a échoué : YunoHost a pu télécharger la ressource 'fr' (http://www.pmwiki.org/pub/pmwiki/i18n/i18n-fr.zip) pour pmwiki, malheureusement celle-ci ne correspond pas à la somme des contrôles attendue. Cela peut signifier qu'une défaillance temporaire du réseau s'est produite sur votre serveur, OU que la ressource a été modifiée par le mainteneur de l'application en amont (ou un acteur malveillant ?) et que les responsables du paquet de cette application pour YunoHost doivent investiguer et mettre à jour le manifeste de l'application pour indiquer ce changement.
    Somme de contrôle sha256 attendue : edc1e591f0d901cda90d4ab3a4e6b4d0f6a910454a35837a15a361dc6520354d
    Somme de contrôle sha256 téléchargée : 0bedd50a56777b8568f2e7a8e291aa5c38c62a9a5c62c9d30d53a7c9eef5c004
    Taille du fichier téléchargé : 684K
72089 INFO L'opération 'Installer l'application 'pmwiki'' a échoué ! Pour obtenir de l'aide, merci de partager le journal de l'opération en utilisant la commande 'yunohost log share 20240809-155906-app_install-pmwiki'
72103 DEBUG action [636510.1] executed in 71.948s
72103 DEBUG lock has been released
72103 ERROR L'opération 'Installer l'application 'pmwiki'' a échoué ! Pour obtenir de l'aide, merci de partager le journal de l'opération en utilisant la commande 'yunohost log share 20240809-155906-app_install-pmwiki'

I opened a new issue, let me apologized (and let me know) if this is not the appropriate way to proceed.

Thank's in advance,
Alain

**Comment by ericgaspar** [comment]
upstream repo for the translation package keep changing 🙄 #19 should fix it (for now)
